### ISSUE TITLE
set up a staging server

### ISSUE THREAD

**Issue by dpritchett** [CoVital-Project/node-mongo-backend-spike#2]
consider heroku or fargate, will need a mongo server available

**Comment by dpritchett** [comment]
@haggy is looking to spin up a host somewhere that we can deploy to via a `docker pull` from a public repo for our initial staging setup.

@xtebs do you already have a DO droplet for this purpose? If so can you share access?

**Comment by haggy** [comment]
@dpritchett and I had a good conversation around deployment strategies and initial tech. Im just going to summarize that here for recording purposes:

- Services and databases built and maintained as docker images
- How we initially run and manage the docker containers is open to discussion but a simple setup using `docker-compose` could work very well for us out of the gate
- A CI/CD (such as circleci) will be used to build the images and will push them to our docker repo
- When developers want to deploy, a simple docker pull from the VPS running that service will get the latest image. You can then use standard `docker-compose` commands to upgrade the running container to the latest image

**Comment by xtebs** [comment]
Hey guys, at the moment I have nothing assembled on a VPS. I was thinking of just put together a node and mongoDB on a VPS in DO for testing, without any docker. If you guys want to invest some time on this kind of devops right away, I can create the VPS and share the ssh with you guys. @haggy do you want to take care of the "dockerization"? 
If so I will create a droplet specifically for this.

**Comment by haggy** [comment]
@xtebs Yea getting a basic docker-compose setup is super fast and it'll let us at least manage containers clearly instead of having to wrangle rogue procs on the box. I'd be happy to install and get docker going on the VPS. @dpritchett are we going to just use GH docker repo for the images?

**Comment by dpritchett** [comment]
Not sure I follow. Does GitHub packages provide a docker container registry now?

If you're asking how we'll build the images on each `master` merge then I'd imagine we'll set up another GitHub action to build+upload the images to a public Docker Hub repository.

**Comment by haggy** [comment]
> Does GitHub packages provide a docker container registry now?

Yup!
https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-docker-for-use-with-github-packages

**Comment by dpritchett** [comment]
closed by #35
