### ISSUE TITLE
Dart generation file was removed from the code base

### ISSUE THREAD

**Issue by MalcolmMielle** [CoVital-Project/node-mongo-backend-spike#44]
Hi,

the script for generating dart code has been removed in 825aee8111a1db3cc7f11f489ced93bea16601f6

Was this on purpose?

**Comment by dpritchett** [comment]
Yes! If you need the latest it's better that you clone this repo, pull the latest `master`, and then run `make dart_client`.  Checking in all of the per-language client bindings on each commit didn't seem like the right path to me.

Let me know if this workflow is problematic and I'll see about prioritizing the time to deliver a more automated flow.

**Comment by dpritchett** [comment]
![image](https://user-images.githubusercontent.com/147981/77859032-abee2700-71cc-11ea-8659-afe8d6e0faa3.png)

**Comment by dpritchett** [comment]
Looks like I misread your question.  You can still generate the dart code, I just repurposed that script to support multiple languages via the makefile.
