### ISSUE TITLE
Discussion: qualitative fields to collect for data collection app

### ISSUE THREAD

**Issue by YoniSchirris** [CoVital-Project/node-mongo-backend-spike#56]
Let's finalize the qualitative data collection in this thread, and leave the other thread to the technical discussions. After finalizing, we can comm to backend team

# Data needed

## Base measures

* Camera recording - video
* SpO2 ground truth measurements - float
* Heart rate ground truth measurements - int
* Reference of the ground truth measurement system - String
* Brand of the ground truth measurement system - String
* Phone brand - String
* Phone reference - String

## User data - optional but highly recommended

* age - int
* weight - double
* sex - enum
~* skin color/ethnicity - enum~
* height (dropdown: cm / inches / ft) - int 

## Others

* IMU measurements - sensor measurements include: accelerometer (double), gyroscope (double), and the timestamps (DateTime String)
* COVID: enum
* Asthma: enum
* COPD: enum
* smoker: enum
* any cardiovascular disease: enum
* shortness of breath: enum

Suggested by Sri:
* Interstitial lung disease/sarcoidosis/idiopathic pulmonary fibrosis
* Lymphangioleiomyomatosis (LAM)
* Pulmonary vascular disease
* Cystic fibrosis
* Pulmonary hypertension

**Comment by haggy** [comment]
> Reference of the ground truth measurement system
> Phone reference

What are these references? I saw that in the collection app as well.

**Comment by YoniSchirris** [comment]
Note that this thread is also meant for the data collection app. I was hoping to get more 'product' and 'MD UX" and "data science" discussions here, so that wecan finalize what our base requirements are, and can then communicate that to the backend team :)

**Comment by MalcolmMielle** [comment]
@haggy the reference are the brand and model number usually. For my phone it'll be Motorola - Motorola one for example. The idea is that in testing if it comes down to it, we can find which phone give good measurements and which don't

**Comment by gianlucatruda** [comment]
Considering how much of a factor fever is in Covid-19, perhaps body temperature (at most recent measurement)?

**Comment by YoniSchirris** [comment]
This is for the data collection app, not the user facing app. I think this is very important for the user facing app to give advice about possibility of covid, not necessarily for our predictive model of getting spo2.

**Comment by YoniSchirris** [comment]
@MalcolmMielle Added Sri's suggestions of comorbidities

**Comment by haggy** [comment]
@YoniSchirris This has been inactive for a bit, should we close it out? Have all questions been answered?

**Comment by MalcolmMielle** [comment]
Yes, in any case it should be moved to the data collection app
