### ISSUE TITLE
Need Initial NoSQL schema layout for receiving data from the HealthWatcher APK

### ISSUE THREAD

**Issue by dpritchett** [CoVital-Project/node-mongo-backend-spike#6]

**Comment by palfaiate** [comment]
Structure example:
{
  "age": 25,
  "diagnoses": [
    {
      "questions": [{"a":"a","timestamp":"2020-03-17T13:32:09+00:00"},{"b":"b","timestamp":"2020-03-17T13:32:09+00:00"}]
      "readings": [
        {
          "BPM": 75,
          "location": "+40.6894-074.0447",
          "SPO2": 97,
          "temperature": 37.5,
          "timestamp": "2020-03-17T13:32:09+00:00"
        }
      ],
      "status": [
        {
          "action": "TBD",
          "status": "Processing",
          "timestamp": "2020-03-17T13:32:09+00:00"
        },
        {
          "action": "None",
          "status": "Infection Unlikely",
          "timestamp": "2020-03-17T14:32:09+00:00"
        }
      ],
      "symptoms": [
        {
          "symptom": "Fever",
          "status": [
          {
            "timestamp": "2020-03-17T14:32:09+00:00",
            "severity": "Mild"
          }
          ]
        }
      ],
      "timestamp": "2020-03-17T13:32:09+00:00"
    }
  ],
  "gender": "male",
  "uid": "345-45-5656-64dgdff"
}

**Comment by dpritchett** [comment]
@claucookie we'd like to give you a place to upload the data collected from Android. Looks like this ticket will be the twin of https://github.com/CoVital-Project/HealthWatcher/issues/4 .

Any special requests or guidance you can give us on what you're seeing on the Android side?

**Comment by dpritchett** [comment]
cc @xtebs @Quantomicus from our slack thread on this same topic

**Comment by xtebs** [comment]
Yep we are using what @palfaiate just posted

**Comment by haggy** [comment]
Closing this as many things have changed and the data here is out of date. We can open a new issue when the time is right.
