### ISSUE TITLE
Multiple PR's failing due to missing circleci config

### ISSUE THREAD

**Issue by haggy** [CoVital-Project/node-mongo-backend-spike#62]
I checked multiple branches and it doesn't appear that it ever existed but I could be missing something. 

The failing PR's (so far): https://github.com/CoVital-Project/pulse-ox-data-collection-web-service/pull/60 and https://github.com/CoVital-Project/pulse-ox-data-collection-web-service/pull/61

![image](https://user-images.githubusercontent.com/2634904/78096689-4b1b4600-73a8-11ea-99d6-bf8dcfb238a0.png)

**Comment by dpritchett** [comment]
Removed the CircleCI integration. Thanks for the heads up!
