### ISSUE TITLE
Discussion: Enable others ( local contacts, researchers, journalists, doctors) to see and download the data we are collecting

### ISSUE THREAD

**Issue by dariodaprile** [CoVital-Project/node-mongo-backend-spike#69]
Thinking two use cases:
The 1st use case is a Brazilian MIT researcher that needs to get the raw data to run separate research about SP02% and illness condition. 

The 2nd use case is an Italian contact that wants to share with the local MDs in the territory a URL where to compare of the accuracy of our mobile SP02% vs the measure from the finger pulse oximeter devices. 

No registration required considering the data have no PII.

**Comment by YoniSchirris** [comment]
To start, we can do a weekly dump manually on https://zenodo.org/. This is what I'd like to do for the students working on the project, anyway.

**Comment by palfaiate** [comment]
We could have an API endpoint where you would have to specify the list of fields required and it would reply with the data required.

**Comment by haggy** [comment]
@dariodaprile I'm +1 to @YoniSchirris's solution for now. Once we get consistent activity on the `zenodo` org we can take in user feedback and possibly automate the uploads if it's something we need to do longterm. Does that sound reasonable?
